name: Checkout repo and llmops utils

description: Checkout current repo and all additional llmops utils from template repo

inputs:
  llmops_repository:
    description: "The url to llmops promptflow template repository"
    default: microsoft/llmops-promptflow-template
  llmops_ref:
    description: "The branch branch/tag/SHA to checkout from llmops promptflow template repository"
    required: false

runs:
  using: composite
  steps:
  - name: Checkout current repo
    uses: actions/checkout@v4

  - name: Checkout llmops utils from template repository
    if: ${{ github.repository != inputs.llmops_repository }}  # Skip if current repo is actually template repo
    uses: actions/checkout@v4
    with:
      repository: ${{ inputs.llmops_repository }}
      ref: ${{ inputs.llmops_ref }}
      sparse-checkout: |
        .github/actions/
        .github/requirements/
        llmops/
      sparse-checkout-cone-mode: false
      path: TMPCHECKOUT

  - name: Move checked out files to root
    if: ${{ github.repository != inputs.llmops_repository }}  # Skip if current repo is actually template repo
    shell: bash
    run: |
      # Move checked out files to root
      rm -rf TMPCHECKOUT/.git
      # If file exists in current repo, it should not be overriden
      # Merging folders not supported with mv, so explicitly moving contents of each of them
      mkdir -p .github/actions/
      mv TMPCHECKOUT/.github/actions/* .github/actions/ --no-clobber --verbose
      mkdir -p .github/requirements/
      mv TMPCHECKOUT/.github/requirements/* .github/requirements/ --no-clobber --verbose
      mkdir -p llmops/
      mv TMPCHECKOUT/llmops/* llmops/ --no-clobber --verbose
      echo "--- Files from llmops template skipped in checkout due to already existing files: ---"
      find TMPCHECKOUT/
      echo "------"
      rm -rf TMPCHECKOUT/
